[tool.poetry]
name = "meteobeguda"
version = "0.1.0"
description = ""
authors = ["Alberto Camara <camara@protonmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.27.1"
pandas = "^1.4.2"
streamlit = "^1.8.1"
typer = "^0.4.1"
plotly-express = "^0.4.1"

[tool.poetry.dev-dependencies]
pytest = "^7.1.1"
pytest-cov = "^3.0.0"
requests-mock = "^1.9.3"
black = "^22.3.0"
types-requests = "^2.27.16"
flake8 = "^4.0.1"
bandit = "^1.7.4"
mypy = "^0.942"
hypothesis = "^6.43.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
