name: Run tests

on:
  - pull_request

jobs:
  pytest-setup:
    uses: ./.github/workflows/setup-uv.yml
  pytest:
    needs: pytest-setup
    runs-on: ubuntu-latest
    steps:
    - name: Pytest
      run: uv run pytest -v --cov=src

  ty-setup:
    uses: ./.github/workflows/setup-uv.yml
  ty:
    needs: ty-setup
    runs-on: ubuntu-latest
    steps:
      - name: Ty
        run: uv run ty check

  ruff-setup:
    uses: ./.github/workflows/setup-uv.yml
  ruff:
    needs: ruff-setup
    runs-on: ubuntu-latest
    steps:
    - name: ruff
      run: uv run ruff check .

  ruff-format-setup:
    uses: ./.github/workflows/setup-uv.yml
  ruff-format:
    needs: ruff-format-setup
    runs-on: ubuntu-latest
    steps:
    - name: ruff
      run: uv run ruff format --check .

  bandit-setup:
    uses: ./.github/workflows/setup-uv.yml
  bandit:
    needs: bandit-setup
    runs-on: ubuntu-latest
    steps:
    - name: Bandit
      run: uv run bandit .
