name: Run tests

on:
  - pull_request

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: .github/actions/setup-uv
      - name: Pytest
        run: uv run pytest -v --cov=src
  ty:
    runs-on: ubuntu-latest
    steps:
      - uses: .github/actions/setup-uv
      - name: Ty
        run: uv run ty check
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: .github/actions/setup-uv
      - name: ruff
        run: uv run ruff check .
  ruff-format:
    runs-on: ubuntu-latest
    steps:
      - uses: .github/actions/setup-uv
      - name: ruff
        run: uv run ruff format --check .
  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: .github/actions/setup-uv
      - name: Bandit
        run: uv run bandit .
